spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss007_db?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# hikaricp 自定义配置，对应 hikariconfig 配置属性类
#    hikari:
#      minimum-idle: 10 # 池中维护的最小空闲连接数，默认为 10 个。
#      maximum-pool-size: 15 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
